[project]
name = "sqrl-mortgage-analysis"
version = "0.1.0"
description = "Example Squirrels project of mortgage analytics"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scipy>=1.16.1",
    "squirrels>=0.5.2",
]
