[project]
name = "sqrl-expenses"
version = "0.1.0"
description = "Example Squirrels project for expenses analytics"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "squirrels>=0.5.4",
]
