[project]
name = "sqrl-expenses"
version = "0.1.0"
description = "Example Squirrels project for expenses analytics"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "squirrels",
]

[tool.uv.sources]
squirrels = { git = "https://github.com/squirrels-analytics/squirrels" }
